--Data definition language
--mysql ddl
--CREATE  TABLE users (
--  username VARCHAR(45) NOT NULL ,
--  password VARCHAR(45) NOT NULL ,
--  enabled TINYINT NOT NULL DEFAULT 1 ,
--  PRIMARY KEY (username)
--);
--CREATE TABLE user_roles (
--  user_role_id int(11) NOT NULL AUTO_INCREMENT,
--  username varchar(45) NOT NULL,
--  role varchar(45) NOT NULL,
--  PRIMARY KEY (user_role_id),
--  UNIQUE KEY uni_username_role (role,username),
--  KEY fk_username_idx (username),
--  CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users (username)
--);

--h2 database ddl
DROP INDEX fk_username_idx IF EXISTS;
DROP TABLE user_roles IF EXISTS;
DROP TABLE users IF EXISTS;

CREATE  TABLE users (
	username VARCHAR(45) NOT NULL, 
	password VARCHAR(60) NOT NULL, 
	enabled BOOLEAN NOT NULL, 
	PRIMARY KEY (username)
);
CREATE TABLE user_roles (
	user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	username VARCHAR(45) NOT NULL, 
	role VARCHAR(45) NOT NULL, 
	PRIMARY KEY (user_role_id),
	CONSTRAINT uni_username_role UNIQUE(role,username),
	FOREIGN KEY (username) REFERENCES users (username)
);
CREATE INDEX fk_username_idx on user_roles(username);


