DROP TABLE IF EXISTS stock;
CREATE TABLE stock (
  STOCK_ID SERIAL,
  STOCK_CODE VARCHAR(10) NOT NULL,
  STOCK_NAME VARCHAR(20) NOT NULL,
  CONSTRAINT PK_STOCK_ID PRIMARY KEY (STOCK_ID),
  CONSTRAINT UN_STOCK_CODE UNIQUE (STOCK_CODE),
  CONSTRAINT UN_STOCK_NAME UNIQUE (STOCK_NAME)
);


DELETE FROM stock;
SELECT * FROM stock;
