--Data definition language
drop table USERS if exists;
create table USERS (ID bigint generated by default as identity, USER_LOGIN varchar(20) not null, USER_PASS varchar(30) not null, AGE integer not null, primary key (ID));
